name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Unnecessary to check the build twice
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: CI=false npm run build
 
    - name: Run tests
      run: npm run test -- --passWithNoTests
      # Remove "--passWithNoTests" when tests are added

